openapi: 3.0.3
info:
  title: Unhas Gacor 77
  description: Online slot machine simulation
  version: 1.0.0

paths:
  /register:
    post:
      tags:
        - User
      description: Register user information
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
      responses:
        201:
          description: success register user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      message:
                        type: string
        400:
          description: failed to register user information because of invalid request body
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: VALIDATION_ERROR
                      message:
                        type: string
        401:
          description: Unauthorized - The user must be authenticated to access this resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                AuthorizationError:
                  $ref: "#/components/examples/authRequiredError"
  /profile:
    get:
      tags:
        - User
      description: Get user information
      responses:
        200:
          description: success get user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      fullName:
                        type: string
                      money:
                        type: number
        401:
          description: Unauthorized - The user must be authenticated to access this resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                AuthorizationError:
                  $ref: "#/components/examples/authRequiredError"
        409:
          description: Failed to get the user information due to incomplete user profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: INCOMPLETE_PROFILE
                      message:
                        type: string
  /money:
    get:
      tags:
        - User
      description: Get the amount of money the user have
      responses:
        200:
          description: success get the user money information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      money:
                        type: number
        401:
          description: Unauthorized - The user must be authenticated to access this resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                AuthorizationError:
                  $ref: "#/components/examples/authRequiredError"
        409:
          description: Failed to get the user information due to incomplete user profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: INCOMPLETE_PROFILE

  /bonus:
    get:
      tags: [User]
      description: Mengecek apakah pengguna berhak untuk klaim bonus harian (cooldown 24 jam sejak klaim terakhir)
      responses:
        200:
          description: Berhasil mendapatkan status kelayakan klaim bonus harian
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: "#/components/schemas/BonusStatus"
        401:
          description: Tidak diizinkan - Pengguna harus login untuk mengakses resource ini.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                AuthorizationError:
                  $ref: "#/components/examples/authRequiredError"
        409:
          description: Gagal mengecek bonus harian karena profil pengguna belum lengkap
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                IncompleteProfile:
                  value:
                    success: false
                    error:
                      code: INCOMPLETE_PROFILE
                      message: "Profil pengguna tidak ditemukan"

    post:
      tags: [User]
      description: Mengklaim bonus harian pengguna (cooldown persis 24 jam sejak klaim terakhir)
      responses:
        200:
          description: Berhasil klaim bonus harian
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: "#/components/schemas/BonusClaimResponse"
              examples:
                Success:
                  value:
                    success: true
                    data:
                      bonus: 100000
                      money: 150000
                      lastBonusTimestamp: "2025-08-09T06:05:15.000Z"
                      nextEligibleAt: "2025-08-10T06:05:15.000Z"
                      message: "Berhasil klaim! Bisa klaim lagi setelah 24 jam."
        401:
          description: Tidak diizinkan - Pengguna harus login untuk mengakses resource ini.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                AuthorizationError:
                  $ref: "#/components/examples/authRequiredError"
        403:
          description: Dilarang - Pengguna belum bisa klaim bonus (cooldown belum selesai)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                AlreadyClaimed:
                  value:
                    success: false
                    error:
                      code: UNAUTHORIZED_ACTION
                      message: "Sudah klaim. Coba lagi setelah 24 jam (pada 2025-08-10T06:05:15.000Z)."
        409:
          description: Gagal klaim bonus harian karena profil pengguna belum lengkap
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                IncompleteProfile:
                  value:
                    success: false
                    error:
                      code: INCOMPLETE_PROFILE
                      message: "Profil pengguna tidak ditemukan"

  /spin:
    post:
      tags:
        - Game
      description: Spin the slot machine
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                betAmount:
                  type: number
      responses:
        200:
          description: success spin the slot machine
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      reward:
                        type: number
                      balance:
                        type: number
                      result:
                        type: array
                        items:
                          type: number
        401:
          description: Unauthorized - The user must be authenticated to access this resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                AuthorizationError:
                  $ref: "#/components/examples/authRequiredError"
        403:
          description: Forbidden - The user is not authorized to do the action
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Forbidden:
                  $ref: "#/components/examples/unauthorizedError"

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: array
              items:
                type: object

    BonusStatus:
      type: object
      properties:
        eligible:
          type: boolean
          description: Apakah pengguna bisa klaim bonus sekarang (elapsed >= 24 jam)
          example: true
        lastBonusTimestamp:
          type: string
          format: date-time
          nullable: true
          description: Waktu klaim bonus terakhir dalam format ISO; null jika belum pernah klaim
          example: "2025-08-09T06:05:15.000Z"
        nextEligibleAt:
          type: string
          format: date-time
          description: Waktu kapan pengguna bisa klaim lagi (sekarang atau last+24 jam)
          example: "2025-08-10T06:05:15.000Z"
        message:
          type: string
          example: "Bonus tersedia!"

    BonusClaimResponse:
      type: object
      properties:
        bonus:
          type: integer
          description: Jumlah bonus yang diberikan
          example: 100000
        money:
          type: integer
          description: Saldo pengguna setelah klaim
          example: 150000
        lastBonusTimestamp:
          type: string
          format: date-time
          description: Waktu klaim bonus dalam format ISO
          example: "2025-08-09T06:05:15.000Z"
        nextEligibleAt:
          type: string
          format: date-time
          description: Waktu kapan bisa klaim lagi (lastBonusTimestamp + 24 jam)
          example: "2025-08-10T06:05:15.000Z"
        message:
          type: string
          example: "Berhasil klaim! Bisa klaim lagi setelah 24 jam."

  examples:
    authRequiredError:
      value:
        success: false
        error:
          code: AUTH_REQUIRED
          message: "You have to be authenticated to access this resource"
    unauthorizedError:
      value:
        success: false
        error:
          code: UNAUTHORIZED_ACTION
          message: "You are not authorized to do the action"
