openapi: 3.0.3
info: 
  title: Unhas Gacor 77
  description: Online slot machine simulation
  version: 1.0.0
  
paths:
  /register:
    post:
      tags:
        - User
      description: Register user information
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
      responses:
        201:
          description: success register user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      message:
                        type: string
        400:
          description: failed to register user information because of invalid request body
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      code: 
                        type: string
                        example: VALIDATION_ERROR
                      message:
                        type: string
        401:
          description: Unauthorized - The user must be authenticated to access this resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                AuthorizationError:
                  $ref: '#/components/examples/authRequiredError'
  /profile:
    get:
      tags:
      - User
      description: Get user information
      responses:
        200:
          description: success get user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      fullName: 
                        type: string
                      money:
                        type: number
        401:
          description: Unauthorized - The user must be authenticated to access this resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                AuthorizationError:
                  $ref: '#/components/examples/authRequiredError'
        409:
          description: Failed to get the user information due to incomplete user profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: object
                    properties:
                      code: 
                        type: string
                        example: INCOMPLETE_PROFILE
                      message:
                        type: string                
  /money:
    get:
      tags:
        - User
      description: Get the amount of money the user have
      responses:
        200:
          description: success get the user money information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  data:
                    type: object
                    properties:
                      money:
                        type: number
        401:
          description: Unauthorized - The user must be authenticated to access this resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                AuthorizationError:
                  $ref: '#/components/examples/authRequiredError'
        409:
          description: Failed to get the user information due to incomplete user profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: object
                    properties:
                      code: 
                        type: string
                        example: INCOMPLETE_PROFILE
  
  /bonus:
    get:
      tags:
      - User
      description: Check if the user is eliglbe for the bonus
      responses:
        200:
          description: success get the user's bonus eligibility status
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  data:
                    type: object
                    properties:
                      eligible:
                        type: boolean
        401:
          description: Unauthorized - The user must be authenticated to access this resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                AuthorizationError:
                  $ref: '#/components/examples/authRequiredError'
    post:
      tags:
      - User
      description: Get bonus for the user
      responses:
        200:
          description: success receive the bonus
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  data:
                    type: object
                    properties:
                      bonus:
                        type: integer
                        example: 10000
                      money:
                        type: integer
                        example: 11000
        401:
          description: Unauthorized - The user must be authenticated to access this resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                AuthorizationError:
                  $ref: '#/components/examples/authRequiredError'
        
        403:
          description: Forbidden - The user is not authorized to do the action
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Forbidden:
                  $ref: '#/components/examples/unauthorizedError'
  /spin:
    post:
      tags:
      - Game
      description: Spin the slot machine
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                betAmount:
                  type: number
      responses:
        200:
          description: success spin the slot machine
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data: 
                    type: object
                    properties:
                      reward:
                        type: number
                      result:
                        type: array
                        items:
                          type: number
        401:
          description: Unauthorized - The user must be authenticated to access this resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                AuthorizationError:
                  $ref: '#/components/examples/authRequiredError'
        403:
          description: Forbidden - The user is not authorized to do the action
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Forbidden:
                  $ref: '#/components/examples/unauthorizedError'
      
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error: 
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: array
              items:
                type: object
  examples:
    authRequiredError:
      value:
        success: false
        error: 
          code: AUTH_REQUIRED
          message: You have to authenticated to access this resource
    unauthorizedError:
      value:
        success: false
        error: 
          code: UNAUTHORIZED_ACTION
          message: You are not authorized to do the action
